name: Create New Version
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What kind of change is this?
        options: 
        - major
        - minor
        - patch
        default: patch

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create new version
        run: npm version patch
      - name: push new tag
        run: |
          git config --global user.name 'PeterNMcArthur'
          git config --global user.email 'PeterNMcArthur@users.noreply.github.com'
          git push --tags
          git push
