name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create new version
        run: npm version patch
      - name: push new tag
        run: |
          git config --global user.name 'Peter'
          git config --global user.email 'PeterNMcArthur@users.noreply.github.com'
          git push --tags
          git push
